replicaCount: 1

service:
  name: urbex-service
  image: homelab.local/urbex-service
  port: 443
  labels:
    security.kubernetes.io/ingress-restriction-scope: "application"
    security.kubernetes.io/egress-restriction-scope: "public"
    app.kubernetes.io/component: "backend"
    app.kubernetes.io/part-of: "urbex-crawler"

frontend:
  name: urbex-ui
  image: homelab.local/urbex-ui
  port: 3000
  labels:
    security.kubernetes.io/ingress-restriction-scope: "public"
    security.kubernetes.io/egress-restriction-scope: "application"
    app.kubernetes.io/component: "frontend"
    app.kubernetes.io/part-of: "urbex-crawler"
  ingress:
    enabled: true
    host: urbexcrawler.codesty.dev
    className: traefik
    tlsSecretName: urbexcrawler-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dev

backend:
  ingress:
    enabled: true
    host: api.urbexcrawler.codesty.dev
    className: traefik
    tlsSecretName: urbexcrawler-backend-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-dev
