replicaCount: 1

service:
  name: urbex-service
  image: homelab.local/urbex-service
  port: 443
  labels:
    security.kubernetes.io/ingress-restriction-scope: "application"
    security.kubernetes.io/egress-restriction-scope: "public"
    app.kubernetes.io/component: "backend"
    app.kubernetes.io/part-of: "urbex-crawler"

frontend:
  name: urbex-ui
  image: homelab.local/urbex-ui
  port: 3000
  labels:
    security.kubernetes.io/ingress-restriction-scope: "public"
    security.kubernetes.io/egress-restriction-scope: "application"
    app.kubernetes.io/component: "frontend"
    app.kubernetes.io/part-of: "urbex-crawler"

ingress:
  enabled: true
  annotations:
    cert-manager.io/common-name: urbexcrawler.codesty.dev
    cert-manager.io/secret-name: urbexcrawler-tls   
    cert-manager.io/cluster-issuer: selfsigned-issuer 
  hosts:
    - host: urbexcrawler.codesty.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - urbexcrawler.codesty.dev
      secretName: urbexcrawler-tls
